@api= http://localhost:5400/extramercs
### ruta inicial /videos
GET {{api}}

### crear un video
POST  {{api}}
Content-Type: application/json

[
  {
    "_id": "6212c45a7a490e8a2504239c",
    "name": "Preservativos",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:44:42.812Z",
    "updatedAt": "2022-02-20T22:44:42.812Z"
  },
  {
    "_id": "6212c4bb756e3ae0e0e70b60",
    "name": "Cervezas",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:46:19.831Z",
    "updatedAt": "2022-02-20T22:46:19.831Z"
  },
  {
    "_id": "6212c4ca756e3ae0e0e70b63",
    "name": "Refrescos",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:46:34.066Z",
    "updatedAt": "2022-02-20T22:46:34.066Z"
  }
]

### actualizar un video
PUT {{api}}
Content-Type: application/json

[
  {
    "_id": "6212c45a7a490e8a2504239c",
    "name": "Preservativos",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:44:42.812Z",
    "updatedAt": "2022-02-20T22:44:42.812Z"
  },
  {
    "_id": "6212c4bb756e3ae0e0e70b60",
    "name": "Cervezas",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:46:19.831Z",
    "updatedAt": "2022-02-20T22:46:19.831Z"
  },
  {
    "_id": "6212c4ca756e3ae0e0e70b63",
    "name": "Refrescos",
    "qty": 10,
    "priceBuy": 2,
    "priceSell": 5,
    "createdAt": "2022-02-20T22:46:34.066Z",
    "updatedAt": "2022-02-20T22:46:34.066Z"
  }
]

### solicitud de un solo video por id
GET {{api}}/60a7cd6890f1c6441c998381

### borrar un video
DELETE {{api}}/60a7daaf00205b4384ecdf
