@api= http://localhost:5400/habitaciones
### ruta inicial /videos
GET {{api}}

### solicitud de un solo video por id
GET {{api}}/60a7cd6890f1c6441c998381

### crear un video
POST  {{api}}
Content-Type: application/json

{
    "number": 22,
    "status": "libre",
    "priceFraction": 50,
    "priceFull": 60,
    "timesRented": 0
}

### borrar un video
DELETE {{api}}/60a7daaf00205b4384ecdf

### actualizar un video
PUT {{api}}
Content-Type: application/json

{
    "_id": "621150e736e2f017c65fc4b3",
    "number": 2,
    "status": "libre",
    "priceFraction": 50,
    "priceFull": 60,
    "timesRented": 0
}
###
GET https://api.openweathermap.org/data/2.5/weather?q=Berlin&appid=228c7ee5dde339838102bc6cbbd058ba&units=metric

###
GET https://www.amazon.com/dp/B07QV2V7PR?%2AVersion%2A=1&%2Aentries%2A=0&ie=UTF8&language=es_US&viewID=